RegisterNetEvent("playerConnecting")

AddEventHandler("playerConnecting", function(name, kickreason, deferrals)
    License_Identifier = GetPlayerIdentifier(source, 0)
    print(License_Identifier)
    License_Identifier = GetPlayerIdentifier(source, 1)
    print(License_Identifier)
    License_Identifier = GetPlayerIdentifier(source, 2)
    print(License_Identifier)
    License_Identifier = GetPlayerIdentifier(source, 3)
    print(License_Identifier)
    License_Identifier = GetPlayerIdentifier(source, 4)
    print(License_Identifier)
    License_Identifier = GetPlayerIdentifier(source, 5)
    print(License_Identifier)
end)